id: A0D54693E
title: 'MSV 1,16: Adhikaraṇavastu'
type: translation
pechas:
- I881BA24E
- IC4F00E4B
source_metadata:
  languages:
  - bo
  datatype: PlainText
  created_at: 2023-02-09 15:11:18.755466
  last_modified_at: 2023-02-09 15:11:18.755498
alignment_to_base:
  I881BA24E/ECE7: 74C5
  IC4F00E4B/7C7C: 74C5
